/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-05-08 11:13:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1522024768157L));
    _jspx_dependants.put("jar:file:/C:/Users/smbil/Desktop/WebFramework/WebFramework/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/eStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-wrapper\">\r\n");
      out.write("\t<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t<img class=\"first-slide\"\r\n");
      out.write("\t\t\t\t\tsrc=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\"\r\n");
      out.write("\t\t\t\t\talt=\"First slide\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption text-left\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Example headline.</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>Cras justo odio, dapibus ac facilisis in, egestas eget\r\n");
      out.write("\t\t\t\t\t\t\tquam. Donec id elit non mi porta gravida at eget metus. Nullam id\r\n");
      out.write("\t\t\t\t\t\t\tdolor id nibh ultricies vehicula ut id elit.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Sign\r\n");
      out.write("\t\t\t\t\t\t\t\tup today</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t<img class=\"second-slide\"\r\n");
      out.write("\t\t\t\t\tsrc=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\"\r\n");
      out.write("\t\t\t\t\talt=\"Second slide\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Another example headline.</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>Cras justo odio, dapibus ac facilisis in, egestas eget\r\n");
      out.write("\t\t\t\t\t\t\tquam. Donec id elit non mi porta gravida at eget metus. Nullam id\r\n");
      out.write("\t\t\t\t\t\t\tdolor id nibh ultricies vehicula ut id elit.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Learn\r\n");
      out.write("\t\t\t\t\t\t\t\tmore</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t<img class=\"third-slide\"\r\n");
      out.write("\t\t\t\t\tsrc=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\"\r\n");
      out.write("\t\t\t\t\talt=\"Third slide\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption text-right\">\r\n");
      out.write("\t\t\t\t\t\t<h1>One more for good measure.</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>Cras justo odio, dapibus ac facilisis in, egestas eget\r\n");
      out.write("\t\t\t\t\t\t\tquam. Donec id elit non mi porta gravida at eget metus. Nullam id\r\n");
      out.write("\t\t\t\t\t\t\tdolor id nibh ultricies vehicula ut id elit.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Browse\r\n");
      out.write("\t\t\t\t\t\t\t\tgallery</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a class=\"carousel-control-prev\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("\t\t\tdata-slide=\"prev\"> <span class=\"carousel-control-prev-icon\"\r\n");
      out.write("\t\t\taria-hidden=\"true\"></span> <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t</a> <a class=\"carousel-control-next\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("\t\t\tdata-slide=\"next\"> <span class=\"carousel-control-next-icon\"\r\n");
      out.write("\t\t\taria-hidden=\"true\"></span> <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Marketing messaging and featurettes\r\n");
      out.write("      ================================================== -->\r\n");
      out.write("\t<!-- Wrap the rest of the page in another container to center all the content. -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container marketing\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Three columns of text below the carousel -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\tsrc=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\"\r\n");
      out.write("\t\t\t\t\talt=\"Generic placeholder image\" width=\"140\" height=\"140\">\r\n");
      out.write("\t\t\t\t<h2>Heading</h2>\r\n");
      out.write("\t\t\t\t<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis\r\n");
      out.write("\t\t\t\t\teuismod. Nullam id dolor id nibh ultricies vehicula ut id elit.\r\n");
      out.write("\t\t\t\t\tMorbi leo risus, porta ac consectetur ac, vestibulum at eros.\r\n");
      out.write("\t\t\t\t\tPraesent commodo cursus magna.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-secondary\" href=\"#\" role=\"button\">View\r\n");
      out.write("\t\t\t\t\t\tdetails &raquo;</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.col-lg-4 -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\tsrc=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\"\r\n");
      out.write("\t\t\t\t\talt=\"Generic placeholder image\" width=\"140\" height=\"140\">\r\n");
      out.write("\t\t\t\t<h2>Heading</h2>\r\n");
      out.write("\t\t\t\t<p>Duis mollis, est nodn commodo luctus, nisi erat porttitor\r\n");
      out.write("\t\t\t\t\tligula, eget lacinia odio sem nec elit. Cras mattis consectetur\r\n");
      out.write("\t\t\t\t\tpurus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo,\r\n");
      out.write("\t\t\t\t\ttortor mauris condimentum nibh.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-secondary\" href=\"#\" role=\"button\">View\r\n");
      out.write("\t\t\t\t\t\tdetails &raquo;</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.col-lg-4 -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\tsrc=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\"\r\n");
      out.write("\t\t\t\t\talt=\"Generic placeholder image\" width=\"140\" height=\"140\">\r\n");
      out.write("\t\t\t\t<h2>Heading</h2>\r\n");
      out.write("\t\t\t\t<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in,\r\n");
      out.write("\t\t\t\t\tegestas eget quam. Vestibulum id ligula porta felis euismod semper.\r\n");
      out.write("\t\t\t\t\tFusce dapibus, tellus ac cursus commodo, tortor mauris condimentum\r\n");
      out.write("\t\t\t\t\tnibh, ut fermentum massa justo sit amet risus.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-secondary\" href=\"#\" role=\"button\">View\r\n");
      out.write("\t\t\t\t\t\tdetails &raquo;</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.col-lg-4 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- START THE FEATURETTES -->\r\n");
      out.write("\r\n");
      out.write("\t\t<hr class=\"featurette-divider\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row featurette\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<h2 class=\"featurette-heading\">\r\n");
      out.write("\t\t\t\t\tFirst featurette heading. <span class=\"text-muted\">It'll\r\n");
      out.write("\t\t\t\t\t\tblow your mind.</span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<p class=\"lead\">Donec ullamcorper nulla non metus auctor\r\n");
      out.write("\t\t\t\t\tfringilla. Vestibulum id ligula porta felis euismod semper.\r\n");
      out.write("\t\t\t\t\tPraesent commodo cursus magna, vel scelerisque nisl consectetur.\r\n");
      out.write("\t\t\t\t\tFusce dapibus, tellus ac cursus commodo.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<img class=\"featurette-image img-fluid mx-auto\"\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/500x500/auto\" alt=\"Generic placeholder image\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr class=\"featurette-divider\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row featurette\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7 order-md-2\">\r\n");
      out.write("\t\t\t\t<h2 class=\"featurette-heading\">\r\n");
      out.write("\t\t\t\t\tOh yeah, it's that good. <span class=\"text-muted\">See for\r\n");
      out.write("\t\t\t\t\t\tyourself.</span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<p class=\"lead\">Donec ullamcorper nulla non metus auctor\r\n");
      out.write("\t\t\t\t\tfringilla. Vestibulum id ligula porta felis euismod semper.\r\n");
      out.write("\t\t\t\t\tPraesent commodo cursus magna, vel scelerisque nisl consectetur.\r\n");
      out.write("\t\t\t\t\tFusce dapibus, tellus ac cursus commodo.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5 order-md-1\">\r\n");
      out.write("\t\t\t\t<img class=\"featurette-image img-fluid mx-auto\"\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/500x500/auto\" alt=\"Generic placeholder image\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr class=\"featurette-divider\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row featurette\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<h2 class=\"featurette-heading\">\r\n");
      out.write("\t\t\t\t\tAnd lastly, this one. <span class=\"text-muted\">Checkmate.</span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<p class=\"lead\">Donec ullamcorper nulla non metus auctor\r\n");
      out.write("\t\t\t\t\tfringilla. Vestibulum id ligula porta felis euismod semper.\r\n");
      out.write("\t\t\t\t\tPraesent commodo cursus magna, vel scelerisque nisl consectetur.\r\n");
      out.write("\t\t\t\t\tFusce dapibus, tellus ac cursus commodo.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<img class=\"featurette-image img-fluid mx-auto\"\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/500x500/auto\" alt=\"Generic placeholder image\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr class=\"featurette-divider\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- /END THE FEATURETTES -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.container -->\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
